import { NavItem } from "@/types";

export const NAV: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  {
    label: "Society Setup",
    href: "/society",
    icon: "Building2",
    children: [
      { label: "Society Profile", href: "/society/profile" },
      { label: "Buildings / Wings", href: "/society/buildings" },
      { label: "Floors", href: "/society/floors" },
      { label: "Flats", href: "/society/flats" },
      { label: "Society Settings", href: "/society/settings" },
    ],
  },
  {
    label: "Members",
    href: "/members",
    icon: "Users",
    children: [
      { label: "All Members", href: "/members" },
      { label: "Owners", href: "/members/owners" },
      { label: "Co-Owners", href: "/members/co-owners" },
      { label: "Tenants", href: "/members/tenants" },
      { label: "Family Members", href: "/members/family-members" },
      { label: "Member Documents", href: "/members/documents" },
    ],
  },
  {
    label: "Maintenance",
    href: "/maintenance",
    icon: "Wallet",
    children: [
      { label: "Charge Types", href: "/maintenance/charge-types" },
      { label: "Charge Rules", href: "/maintenance/charge-rules" },
      { label: "Non-Occupancy Charges", href: "/maintenance/non-occupancy" },
      { label: "Generate Bills", href: "/maintenance/generate-bills" },
      { label: "All Bills", href: "/maintenance/bills" },
      { label: "Pending Bills", href: "/maintenance/pending-bills" },
      { label: "Defaulters", href: "/maintenance/defaulters" },
      { label: "Late Fees", href: "/maintenance/late-fees" },
    ],
  },
  {
    label: "Payments",
    href: "/payments",
    icon: "CreditCard",
    children: [
      { label: "Collection", href: "/payments/collection" },
      { label: "Payment Transactions", href: "/payments/transactions" },
      { label: "Receipts", href: "/payments/receipts" },
      { label: "Online Payments", href: "/payments/online" },
      { label: "Reconciliation", href: "/payments/reconciliation" },
    ],
  },
  {
    label: "Complaints",
    href: "/complaints",
    icon: "MessageSquareWarning",
    children: [
      { label: "Dashboard", href: "/complaints" },
      { label: "All Complaints", href: "/complaints/all" },
      { label: "Tenant Complaints", href: "/complaints/tenant" },
      { label: "Owner Complaints", href: "/complaints/owner" },
      { label: "Open", href: "/complaints/open" },
      { label: "In Progress", href: "/complaints/in-progress" },
      { label: "Resolved", href: "/complaints/resolved" },
      { label: "Categories", href: "/complaints/categories" },
    ],
  },
  {
    label: "Communication",
    href: "/communication",
    icon: "Megaphone",
    children: [
      { label: "Notices", href: "/communication/notices" },
      { label: "Announcements", href: "/communication/announcements" },
      { label: "Circulars", href: "/communication/circulars" },
      { label: "Notification History", href: "/communication/history" },
    ],
  },
  {
    label: "Parking",
    href: "/parking",
    icon: "SquareParking",
    children: [
      { label: "Parking Slots", href: "/parking/slots" },
      { label: "Parking Allocation", href: "/parking/allocation" },
      { label: "Vehicles", href: "/parking/vehicles" },
      { label: "Paid Parking", href: "/parking/paid" },
      { label: "Parking Coupons", href: "/parking/coupons" },
      { label: "QR / Barcode", href: "/parking/qr-barcode" },
    ],
  },
  {
    label: "Visitor Management",
    href: "/visitors",
    icon: "UserCheck",
    children: [
      { label: "Today's Visitors", href: "/visitors/today" },
      { label: "Visitor History", href: "/visitors/history" },
      { label: "Pre-Approved Visitors", href: "/visitors/pre-approved" },
      { label: "Visitor Reports", href: "/visitors/reports" },
    ],
  },
  {
    label: "Amenities",
    href: "/amenities",
    icon: "Dumbbell",
    children: [
      { label: "Amenity Master", href: "/amenities/master" },
      { label: "Time Slots", href: "/amenities/time-slots" },
      { label: "Bookings", href: "/amenities/bookings" },
      { label: "Booking Calendar", href: "/amenities/calendar" },
    ],
  },
  {
    label: "Vendors",
    href: "/vendors",
    icon: "Truck",
    children: [
      { label: "Vendor Master", href: "/vendors/master" },
      { label: "Vendor Contracts", href: "/vendors/services" },
      { label: "Work Orders", href: "/vendors/work-orders" },
    ],
  },
  {
    label: "Expenses",
    href: "/expenses",
    icon: "ReceiptIndianRupee",
    children: [
      { label: "Expense Categories", href: "/expenses/categories" },
      { label: "Expenses", href: "/expenses/list" },
      { label: "Expense Payments", href: "/expenses/payments" },
    ],
  },
  {
    label: "Inventory",
    href: "/inventory",
    icon: "PackageSearch",
    children: [
      { label: "Categories", href: "/inventory/categories" },
      { label: "Item Master", href: "/inventory/items" },
      { label: "Stock Transactions", href: "/inventory/transactions" },
      { label: "Low Stock", href: "/inventory/low-stock" },
    ],
  },
  {
    label: "Staff & Payroll",
    href: "/staff",
    icon: "ContactRound",
    children: [
      { label: "Staff Master", href: "/staff/master" },
      { label: "Attendance", href: "/staff/attendance" },
      { label: "Payroll", href: "/staff/payroll" },
    ],
  },
  {
    label: "Documents",
    href: "/documents",
    icon: "FolderOpen",
    children: [
      { label: "Society Rules", href: "/documents/society-rules" },
      { label: "Bye-Laws", href: "/documents/bye-laws" },
      { label: "AGM Documents", href: "/documents/agm" },
      { label: "Financial Documents", href: "/documents/financial" },
      { label: "Other Documents", href: "/documents/other" },
    ],
  },
  {
    label: "Accounting",
    href: "/accounting",
    icon: "BookOpenCheck",
    children: [
      { label: "Chart of Accounts", href: "/accounting/accounts" },
      { label: "Vouchers", href: "/accounting/vouchers" },
      { label: "Cash Book", href: "/accounting/cash-book" },
      { label: "Bank Book", href: "/accounting/bank-book" },
      { label: "Trial Balance", href: "/accounting/trial-balance" },
    ],
  },
  {
    label: "Reports",
    href: "/reports",
    icon: "BarChart3",
    children: [
      { label: "Maintenance Collection", href: "/reports/maintenance-collection" },
      { label: "Defaulters", href: "/reports/defaulters" },
      { label: "Expenses", href: "/reports/expenses" },
      { label: "Income & Expense", href: "/reports/income-expense" },
      { label: "Members", href: "/reports/members" },
      { label: "Visitors", href: "/reports/visitors" },
      { label: "Complaints", href: "/reports/complaints" },
      { label: "Parking", href: "/reports/parking" },
    ],
  },
  {
    label: "Users & Roles",
    href: "/users",
    icon: "ShieldCheck",
    children: [
      { label: "Users", href: "/users" },
      { label: "Roles", href: "/users/roles" },
      { label: "Permissions", href: "/users/permissions" },
    ],
  },
  { label: "Settings", href: "/settings", icon: "Settings" },
];
