"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, Database, Download, HardDrive, RefreshCcw, RotateCcw, Server, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/Badge";
import { getSocietySession } from "@/lib/session";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:5000/api/v1";
type Health={databaseStatus:string;databaseLatencyMs:number;processMemoryMb:number;diskFreeBytes:number;diskTotalBytes:number;uptimeSeconds:number;retentionDays:number;details:{node:string;environment:string}};
type Backup={id:number;backup_number:string;file_name:string|null;file_size:number|null;backup_type:string;status:string;started_at:string;completed_at:string|null;created_by_name:string|null;checksum_sha256:string|null};

export default function SystemHealthPage(){
 const router=useRouter();const [health,setHealth]=useState<Health|null>(null);const [backups,setBackups]=useState<Backup[]>([]);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [busy,setBusy]=useState<string|null>(null);
 const token=()=>{const session=getSocietySession();if(!session?.accessToken){router.replace("/login");return null;}if(!session.isSuperAdmin){router.replace("/dashboard");return null;}return session.accessToken;};
 const load=useCallback(async()=>{const access=token();if(!access)return;try{setError("");const [h,b]=await Promise.all([fetch(`${API_URL}/platform/system/health`,{headers:{Authorization:`Bearer ${access}`}}),fetch(`${API_URL}/platform/backups`,{headers:{Authorization:`Bearer ${access}`}})]);const hr=await h.json(),br=await b.json();if(!h.ok||!hr.success)throw new Error(hr.message||"Unable to load system health");if(!b.ok||!br.success)throw new Error(br.message||"Unable to load backups");setHealth(hr.data);setBackups(br.data??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load system data");}},[router]);
 useEffect(()=>{void load();},[load]);
 async function action(key:string,path:string,body?:unknown){const access=token();if(!access)return;setBusy(key);setError("");setSuccess("");try{const response=await fetch(`${API_URL}${path}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${access}`},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.errors?.join(", ")||result.message||"Action failed");setSuccess(result.message+(result.data?.valid===false?" ??? checksum mismatch":""));await load();}catch(e){setError(e instanceof Error?e.message:"Action failed");}finally{setBusy(null);}}
 function download(id:number){const access=token();if(!access)return;fetch(`${API_URL}/platform/backups/${id}/download`,{headers:{Authorization:`Bearer ${access}`}}).then(async response=>{if(!response.ok)throw new Error("Download failed");const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=response.headers.get("content-disposition")?.match(/filename="?([^";]+)"?/)?.[1]||`backup-${id}.sql`;anchor.click();URL.revokeObjectURL(url);}).catch(e=>setError(e.message));}
 async function restore(backup:Backup){const confirmation=window.prompt(`Restore ${backup.file_name}?\nA pre-restore backup will be created.\nType RESTORE BACKUP to continue.`);if(confirmation!=="RESTORE BACKUP")return;await action(`restore-${backup.id}`,`/platform/backups/${backup.id}/restore`,{confirmation});}
 const bytes=(value:number|null|undefined)=>{if(!value)return "0 B";const units=["B","KB","MB","GB","TB"];const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/1024**index).toFixed(1)} ${units[index]}`;};
 const uptime=(seconds:number)=>`${Math.floor(seconds/86400)}d ${Math.floor((seconds%86400)/3600)}h ${Math.floor((seconds%3600)/60)}m`;
 const cards=health?[{label:"Database",value:health.databaseStatus,icon:Database},{label:"DB latency",value:`${health.databaseLatencyMs} ms`,icon:Activity},{label:"Process memory",value:`${health.processMemoryMb} MB`,icon:Server},{label:"Disk free",value:bytes(health.diskFreeBytes),icon:HardDrive},{label:"Uptime",value:uptime(health.uptimeSeconds),icon:RefreshCcw},{label:"Retention",value:`${health.retentionDays} days`,icon:ShieldCheck}]:[];
 return <div><PageHeader title="Backup & System Health" description="Monitor server health and safely manage MySQL database backups." actions={<Button loading={busy==="create"} onClick={()=>void action("create","/platform/backups")}><Database className="h-4 w-4"/>Create Backup</Button>}/>
  {error&&<p className="mb-4 rounded-lg bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{error}</p>}{success&&<p className="mb-4 rounded-lg bg-[var(--color-success-bg)] p-3 text-sm text-[var(--color-success)]">{success}</p>}
  <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(({label,value,icon:Icon})=><Card key={label}><CardBody className="flex items-center gap-3"><div className="rounded-lg bg-[var(--color-primary)]/10 p-2 text-[var(--color-primary)]"><Icon className="h-5 w-5"/></div><div><p className="text-xs text-[var(--color-text-secondary)]">{label}</p><p className="font-semibold">{value}</p></div></CardBody></Card>)}</div>
  <Card><CardHeader title="Database backup history" description="Restore requires checksum verification and creates a pre-restore backup automatically."/><CardBody className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-[var(--color-text-secondary)]">{["Backup","Type","Size","Created By","Started","Status","Actions"].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{backups.map(backup=><tr className="border-t border-[var(--color-border)]" key={backup.id}><td className="px-3 py-3"><div className="font-medium">{backup.file_name||backup.backup_number}</div><div className="text-xs text-[var(--color-text-secondary)]">{backup.backup_number}</div></td><td className="px-3 py-3">{backup.backup_type}</td><td className="px-3 py-3">{bytes(backup.file_size)}</td><td className="px-3 py-3">{backup.created_by_name||"System"}</td><td className="px-3 py-3 whitespace-nowrap">{new Date(backup.started_at).toLocaleString("en-IN")}</td><td className="px-3 py-3"><StatusBadge status={backup.status}/></td><td className="px-3 py-3"><div className="flex gap-2">{["COMPLETED","RESTORED"].includes(backup.status)&&<><Button size="sm" variant="outline" onClick={()=>download(backup.id)}><Download className="h-3.5 w-3.5"/>Download</Button><Button size="sm" variant="outline" loading={busy===`verify-${backup.id}`} onClick={()=>void action(`verify-${backup.id}`,`/platform/backups/${backup.id}/verify`)}><ShieldCheck className="h-3.5 w-3.5"/>Verify</Button><Button size="sm" variant="danger" loading={busy===`restore-${backup.id}`} onClick={()=>void restore(backup)}><RotateCcw className="h-3.5 w-3.5"/>Restore</Button></>}</div></td></tr>)}{backups.length===0&&<tr><td colSpan={7} className="py-12 text-center text-[var(--color-text-secondary)]">No backup created yet.</td></tr>}</tbody></table></CardBody></Card>
 </div>;
}
