import {
  LayoutDashboard,
  Building2,
  Users,
  Wallet,
  CreditCard,
  MessageSquareWarning,
  Megaphone,
  SquareParking,
  UserCheck,
  Dumbbell,
  Truck,
  ReceiptIndianRupee,
  FolderOpen,
  BarChart3,
  ShieldCheck,
  Settings,
  LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Building2,
  Users,
  Wallet,
  CreditCard,
  MessageSquareWarning,
  Megaphone,
  SquareParking,
  UserCheck,
  Dumbbell,
  Truck,
  ReceiptIndianRupee,
  FolderOpen,
  BarChart3,
  ShieldCheck,
  Settings,
};
