"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, KeyRound, LockKeyhole, ShieldAlert, TriangleAlert, Users } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { Select } from "@/components/ui/Input";
import { StatusBadge } from "@/components/ui/Badge";
import { getSocietySession } from "@/lib/session";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:5000/api/v1";
type Summary={audit_count:number;security_event_count:number;open_events:number;high_risk_events:number;locked_users:number;active_sessions:number};
type Event={id:number;event_type:string;severity:string;identifier_masked:string|null;ip_address:string|null;status:string;user_name:string|null;society_name:string|null;created_at:string};
type Audit={id:number;module_name:string;action:string;record_id:number|null;ip_address:string|null;user_name:string|null;society_name:string|null;created_at:string};
type LockedUser={id:number;name:string;mobile:string;email:string|null;failed_login_attempts:number;locked_until:string};
type Data={summary:Summary;events:Event[];auditLogs:Audit[];lockedUsers:LockedUser[];modules:string[]};
const EMPTY:Data={summary:{audit_count:0,security_event_count:0,open_events:0,high_risk_events:0,locked_users:0,active_sessions:0},events:[],auditLogs:[],lockedUsers:[],modules:[]};

export default function SecurityMonitoringPage(){
 const router=useRouter();const [data,setData]=useState<Data>(EMPTY);const [days,setDays]=useState("7");const [severity,setSeverity]=useState("");const [moduleName,setModuleName]=useState("");const [error,setError]=useState("");const [success,setSuccess]=useState("");const [busy,setBusy]=useState<number|null>(null);
 const token=()=>{const session=getSocietySession();if(!session?.accessToken){router.replace("/login");return null;}if(!session.isSuperAdmin){router.replace("/dashboard");return null;}return session.accessToken;};
 const load=useCallback(async()=>{const access=token();if(!access)return;setError("");try{const query=new URLSearchParams({days,limit:"100"});if(severity)query.set("severity",severity);if(moduleName)query.set("module_name",moduleName);const response=await fetch(`${API_URL}/platform/security?${query}`,{headers:{Authorization:`Bearer ${access}`}});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"Unable to load security dashboard");setData(result.data);}catch(e){setError(e instanceof Error?e.message:"Unable to load security dashboard");}},[days,severity,moduleName,router]);
 useEffect(()=>{void load();},[load]);
 async function action(path:string,method="POST",body?:unknown,id?:number){const access=token();if(!access)return;setBusy(id??0);setError("");setSuccess("");try{const response=await fetch(`${API_URL}${path}`,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${access}`},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"Action failed");setSuccess(result.message);await load();}catch(e){setError(e instanceof Error?e.message:"Action failed");}finally{setBusy(null);}}
 const date=(value:string)=>new Date(value).toLocaleString("en-IN");
 const cards=[{label:"Audit activity",value:data.summary.audit_count,icon:Activity},{label:"Security events",value:data.summary.security_event_count,icon:ShieldAlert},{label:"Open alerts",value:data.summary.open_events,icon:TriangleAlert},{label:"High risk",value:data.summary.high_risk_events,icon:ShieldAlert},{label:"Locked users",value:data.summary.locked_users,icon:LockKeyhole},{label:"Active sessions",value:data.summary.active_sessions,icon:Users}];
 return <div><PageHeader title="Security Monitoring" description="Review authentication risks, locked users, active sessions and platform audit activity."/>
  {error&&<p className="mb-4 rounded-lg bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{error}</p>}{success&&<p className="mb-4 rounded-lg bg-[var(--color-success-bg)] p-3 text-sm text-[var(--color-success)]">{success}</p>}
  <Card className="mb-5"><CardBody className="grid gap-3 md:grid-cols-3"><Select label="Period" value={days} onChange={e=>setDays(e.target.value)} options={[{label:"Last 24 hours",value:"1"},{label:"Last 7 days",value:"7"},{label:"Last 30 days",value:"30"},{label:"Last 90 days",value:"90"}]}/><Select label="Severity" value={severity} onChange={e=>setSeverity(e.target.value)} placeholder="All severities" options={["LOW","MEDIUM","HIGH","CRITICAL"].map(x=>({label:x,value:x}))}/><Select label="Audit Module" value={moduleName} onChange={e=>setModuleName(e.target.value)} placeholder="All modules" options={data.modules.map(x=>({label:x,value:x}))}/></CardBody></Card>
  <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(({label,value,icon:Icon})=><Card key={label}><CardBody className="flex items-center gap-3"><div className="rounded-lg bg-[var(--color-primary)]/10 p-2 text-[var(--color-primary)]"><Icon className="h-5 w-5"/></div><div><p className="text-xs text-[var(--color-text-secondary)]">{label}</p><p className="text-xl font-semibold">{value}</p></div></CardBody></Card>)}</div>
  {data.lockedUsers.length>0&&<Card className="mb-5"><CardHeader title="Locked user accounts" description="Unlock only after confirming the user identity."/><CardBody className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-[var(--color-text-secondary)]">{["User","Login","Attempts","Locked Until","Actions"].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.lockedUsers.map(user=><tr className="border-t border-[var(--color-border)]" key={user.id}><td className="px-3 py-3 font-medium">{user.name}</td><td className="px-3 py-3">{user.mobile||user.email}</td><td className="px-3 py-3">{user.failed_login_attempts}</td><td className="px-3 py-3">{date(user.locked_until)}</td><td className="flex gap-2 px-3 py-3"><Button size="sm" loading={busy===user.id} onClick={()=>void action(`/platform/security/users/${user.id}/unlock`,"POST",undefined,user.id)}><KeyRound className="h-3.5 w-3.5"/> Unlock</Button><Button size="sm" variant="outline" onClick={()=>void action(`/platform/security/users/${user.id}/revoke-sessions`,"POST",undefined,user.id)}>Revoke Sessions</Button></td></tr>)}</tbody></table></CardBody></Card>}
  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader title="Security alerts" description="Failed logins and account lock events."/><CardBody className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-[var(--color-text-secondary)]">{["Event","Identity / IP","Risk","Status","Time","Action"].map(x=><th className="px-2 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.events.map(event=><tr className="border-t border-[var(--color-border)]" key={event.id}><td className="px-2 py-3 font-medium">{event.event_type.replaceAll("_"," ")}</td><td className="px-2 py-3"><div>{event.user_name||event.identifier_masked||"Unknown"}</div><div className="text-xs text-[var(--color-text-secondary)]">{event.ip_address||"—"}</div></td><td className="px-2 py-3"><StatusBadge status={event.severity}/></td><td className="px-2 py-3"><StatusBadge status={event.status}/></td><td className="px-2 py-3 whitespace-nowrap">{date(event.created_at)}</td><td className="px-2 py-3">{event.status==="OPEN"&&<Button size="sm" variant="outline" onClick={()=>void action(`/platform/security/events/${event.id}`,"PATCH",{status:"RESOLVED",resolution_note:"Reviewed by Super Admin"},event.id)}>Resolve</Button>}</td></tr>)}{data.events.length===0&&<tr><td colSpan={6} className="py-10 text-center text-[var(--color-text-secondary)]">No security events found.</td></tr>}</tbody></table></CardBody></Card>
   <Card><CardHeader title="Audit trail" description="Recent authenticated business and platform activity."/><CardBody className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-[var(--color-text-secondary)]">{["Module / Action","User","Society","IP","Time"].map(x=><th className="px-2 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.auditLogs.map(log=><tr className="border-t border-[var(--color-border)]" key={log.id}><td className="px-2 py-3"><div className="font-medium">{log.action.replaceAll("_"," ")}</div><div className="text-xs text-[var(--color-text-secondary)]">{log.module_name}</div></td><td className="px-2 py-3">{log.user_name||"System"}</td><td className="px-2 py-3">{log.society_name||"Platform"}</td><td className="px-2 py-3">{log.ip_address||"—"}</td><td className="px-2 py-3 whitespace-nowrap">{date(log.created_at)}</td></tr>)}{data.auditLogs.length===0&&<tr><td colSpan={5} className="py-10 text-center text-[var(--color-text-secondary)]">No audit activity found.</td></tr>}</tbody></table></CardBody></Card>
  </div>
 </div>;
}
