CREATE TABLE IF NOT EXISTS society_complaint_sequences (society_id BIGINT UNSIGNED PRIMARY KEY,next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_complaint_seq_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS society_complaints (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,complaint_number VARCHAR(50) NOT NULL,flat_id BIGINT UNSIGNED NOT NULL,member_id BIGINT UNSIGNED NULL,complainant_name VARCHAR(150) NOT NULL,complainant_type ENUM('OWNER','CO_OWNER','TENANT','OTHER') NOT NULL DEFAULT 'OTHER',category ENUM('PLUMBING','ELECTRICAL','HOUSEKEEPING','SECURITY','LIFT','PARKING','CIVIL','WATER','OTHER') NOT NULL,title VARCHAR(200) NOT NULL,description TEXT NOT NULL,priority ENUM('LOW','MEDIUM','HIGH','URGENT') NOT NULL DEFAULT 'MEDIUM',status ENUM('OPEN','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED','REOPENED','CANCELLED') NOT NULL DEFAULT 'OPEN',assigned_to BIGINT UNSIGNED NULL,resolution_note TEXT NULL,resolved_at DATETIME NULL,closed_at DATETIME NULL,created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_by BIGINT UNSIGNED NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,
 UNIQUE KEY uk_complaint_number(society_id,complaint_number),KEY idx_complaints_status(society_id,status,priority,created_at),KEY idx_complaints_flat(society_id,flat_id),KEY idx_complaints_creator(society_id,created_by),CONSTRAINT fk_complaint_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_complaint_flat FOREIGN KEY(flat_id) REFERENCES flats(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_complaint_member FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT fk_complaint_assignee FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS society_complaint_activity (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,complaint_id BIGINT UNSIGNED NOT NULL,activity_type ENUM('CREATED','ASSIGNED','STATUS_CHANGED','REMARK','RESOLVED','CLOSED','REOPENED') NOT NULL,old_status VARCHAR(30) NULL,new_status VARCHAR(30) NULL,remark TEXT NULL,performed_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_complaint_activity(society_id,complaint_id,created_at),CONSTRAINT fk_activity_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_activity_complaint FOREIGN KEY(complaint_id) REFERENCES society_complaints(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO permissions(permission_name,permission_code,module_name,description,status) VALUES ('View Complaints','society.complaints.view','complaints','View complaints allowed for the current user','ACTIVE'),('Create Complaints','society.complaints.create','complaints','Raise a society complaint','ACTIVE'),('Manage Complaints','society.complaints.manage','complaints','Assign and update complaint workflow','ACTIVE') ON DUPLICATE KEY UPDATE status='ACTIVE';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('SUPER_ADMIN','SOCIETY_ADMIN','CHAIRMAN','SECRETARY') AND p.permission_code LIKE 'society.complaints.%' ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('TREASURER','ACCOUNTANT','SECURITY','RESIDENT') AND p.permission_code IN('society.complaints.view','society.complaints.create') ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
