CREATE TABLE IF NOT EXISTS society_visitors (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,visitor_number VARCHAR(50) NOT NULL,visitor_name VARCHAR(150) NOT NULL,mobile VARCHAR(20) NULL,purpose ENUM('GUEST','DELIVERY','CAB_AUTO','DOMESTIC_HELP','VENDOR','COURIER','SERVICE','OTHER') NOT NULL,flat_id BIGINT UNSIGNED NOT NULL,host_member_id BIGINT UNSIGNED NULL,vehicle_number VARCHAR(30) NULL,id_type ENUM('NONE','AADHAAR','PAN','DRIVING_LICENCE','OTHER') NOT NULL DEFAULT 'NONE',id_last_four VARCHAR(4) NULL,expected_at DATETIME NULL,status ENUM('PENDING_APPROVAL','APPROVED','REJECTED','CHECKED_IN','CHECKED_OUT','CANCELLED') NOT NULL DEFAULT 'PENDING_APPROVAL',approval_note VARCHAR(500) NULL,approved_by BIGINT UNSIGNED NULL,approved_at DATETIME NULL,check_in_at DATETIME NULL,check_in_by BIGINT UNSIGNED NULL,check_out_at DATETIME NULL,check_out_by BIGINT UNSIGNED NULL,created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uk_visitor_number(society_id,visitor_number),KEY idx_visitors_status(society_id,status,created_at),KEY idx_visitors_flat(society_id,flat_id,created_at),CONSTRAINT fk_visitor_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_visitor_flat FOREIGN KEY(flat_id) REFERENCES flats(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_visitor_host FOREIGN KEY(host_member_id) REFERENCES members(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS society_visitor_activity(id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,visitor_id BIGINT UNSIGNED NOT NULL,action ENUM('CREATED','APPROVED','REJECTED','CHECKED_IN','CHECKED_OUT','CANCELLED') NOT NULL,note VARCHAR(500) NULL,performed_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_visitor_activity(society_id,visitor_id,created_at),CONSTRAINT fk_visitor_activity_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_visitor_activity_entry FOREIGN KEY(visitor_id) REFERENCES society_visitors(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS society_visitor_sequences(society_id BIGINT UNSIGNED PRIMARY KEY,next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,CONSTRAINT fk_visitor_sequence_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO permissions(permission_name,permission_code,module_name,description,status) VALUES ('View Visitors','society.visitors.view','visitors','View visitor entries for authorized flats','ACTIVE'),('Create Gate Entry','society.visitors.create','visitors','Create visitor entry at the gate','ACTIVE'),('Approve Visitors','society.visitors.approve','visitors','Approve or reject visitors for own flat','ACTIVE'),('Check In/Out Visitors','society.visitors.gate_action','visitors','Perform visitor check-in and check-out','ACTIVE') ON DUPLICATE KEY UPDATE status='ACTIVE';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('SUPER_ADMIN','SOCIETY_ADMIN','CHAIRMAN','SECRETARY') AND p.permission_code LIKE 'society.visitors.%' ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code='SECURITY' AND p.permission_code IN('society.visitors.view','society.visitors.create','society.visitors.gate_action') ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('TREASURER','ACCOUNTANT','RESIDENT') AND p.permission_code IN('society.visitors.view','society.visitors.approve') ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
