CREATE TABLE IF NOT EXISTS notification_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,template_code VARCHAR(50) NOT NULL,template_name VARCHAR(150) NOT NULL,title_template VARCHAR(200) NOT NULL,message_template VARCHAR(2000) NOT NULL,default_channels JSON NOT NULL,status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_by BIGINT UNSIGNED NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uk_notification_template(society_id,template_code),CONSTRAINT fk_notification_template_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS notification_campaigns (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,title VARCHAR(200) NOT NULL,message VARCHAR(2000) NOT NULL,audience_type ENUM('ALL_USERS','COMMITTEE','RESIDENTS','CUSTOM') NOT NULL,channels JSON NOT NULL,recipient_count INT UNSIGNED NOT NULL DEFAULT 0,delivery_count INT UNSIGNED NOT NULL DEFAULT 0,status ENUM('PROCESSING','QUEUED','COMPLETED','PARTIALLY_FAILED','FAILED') NOT NULL DEFAULT 'PROCESSING',created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME NULL,KEY idx_notification_campaign(society_id,created_at,status),CONSTRAINT fk_notification_campaign_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_notification_preferences (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,email_enabled BOOLEAN NOT NULL DEFAULT TRUE,sms_enabled BOOLEAN NOT NULL DEFAULT TRUE,whatsapp_enabled BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uk_user_notification_preference(society_id,user_id),CONSTRAINT fk_notification_preference_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_notification_preference_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS user_notifications (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,society_id BIGINT UNSIGNED NOT NULL,campaign_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NOT NULL,channel ENUM('IN_APP','EMAIL','SMS','WHATSAPP') NOT NULL,recipient_address VARCHAR(180) NULL,title VARCHAR(200) NOT NULL,message VARCHAR(2000) NOT NULL,status ENUM('QUEUED','SENT','DELIVERED','FAILED','READ') NOT NULL DEFAULT 'QUEUED',attempt_count INT UNSIGNED NOT NULL DEFAULT 0,next_attempt_at DATETIME NULL,provider_message_id VARCHAR(200) NULL,error_message VARCHAR(500) NULL,sent_at DATETIME NULL,delivered_at DATETIME NULL,read_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_campaign_user_channel(campaign_id,user_id,channel),KEY idx_user_in_app(society_id,user_id,channel,status,created_at),KEY idx_notification_outbox(channel,status,next_attempt_at),CONSTRAINT fk_user_notification_society FOREIGN KEY(society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT fk_user_notification_campaign FOREIGN KEY(campaign_id) REFERENCES notification_campaigns(id) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT fk_user_notification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO permissions(permission_name,permission_code,module_name,description,status)VALUES('View Notifications','society.notifications.view','notifications','View personal notifications and preferences','ACTIVE'),('Manage Notifications','society.notifications.manage','notifications','Manage templates and send campaigns','ACTIVE'),('Dispatch Notifications','society.notifications.dispatch','notifications','Dispatch queued external notifications','ACTIVE')ON DUPLICATE KEY UPDATE status='ACTIVE';
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('SUPER_ADMIN','SOCIETY_ADMIN','CHAIRMAN','SECRETARY')AND p.permission_code LIKE'society.notifications.%' ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_code IN('TREASURER','ACCOUNTANT','SECURITY','RESIDENT')AND p.permission_code='society.notifications.view' ON DUPLICATE KEY UPDATE permission_id=VALUES(permission_id);
