"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader"; import { Card } from "@/components/ui/Card"; import { Button } from "@/components/ui/Button"; import { Column, DataTable } from "@/components/ui/DataTable"; import { Drawer } from "@/components/ui/Drawer"; import { Input, Select } from "@/components/ui/Input"; import { StatusBadge } from "@/components/ui/Badge"; import { getSocietySession } from "@/lib/session";
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000/api/v1";
type Option = { member_id: number; name: string; flat_id: number; flat_no: string; building_name: string; wing_name: string };
type Row = { id: number; name: string; relation_type: string; mobile: string | null; primary_member_name: string; flat_no: string; building_name: string; wing_name: string; status: string };
const relations = ["SPOUSE","SON","DAUGHTER","FATHER","MOTHER","BROTHER","SISTER","OTHER"];
export default function FamilyMembersPage() {
  const [rows,setRows]=useState<Row[]>([]); const [options,setOptions]=useState<Option[]>([]); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const [form,setForm]=useState({ primary_member_id:"", flat_id:"", name:"", relation_type:"SPOUSE", mobile:"", email:"", date_of_birth:"" });
  const load=useCallback(async()=>{const session=getSocietySession();if(!session?.accessToken)return setError("Please login and select a society.");try{const h={Authorization:`Bearer ${session.accessToken}`};const [a,b]=await Promise.all([fetch(`${API_URL}/society/member-management/family`,{headers:h}),fetch(`${API_URL}/society/member-management/member-options`,{headers:h})]);const [x,y]=await Promise.all([a.json(),b.json()]);if(!a.ok||!x.success)throw new Error(x.message);if(!b.ok||!y.success)throw new Error(y.message);setRows(x.data??[]);setOptions(y.data??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load family members.");}},[]); useEffect(()=>{void load();},[load]);
  function start(){setForm({primary_member_id:"",flat_id:"",name:"",relation_type:"SPOUSE",mobile:"",email:"",date_of_birth:""});setError("");setSuccess("");setOpen(true);}
  async function submit(e:FormEvent){e.preventDefault();const s=getSocietySession();if(!s?.accessToken)return;setSaving(true);try{const r=await fetch(`${API_URL}/society/member-management/family`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${s.accessToken}`},body:JSON.stringify({...form,primary_member_id:Number(form.primary_member_id),flat_id:Number(form.flat_id)})});const j=await r.json();if(!r.ok||!j.success)throw new Error(Array.isArray(j.errors)?j.errors.join(", "):j.message);setOpen(false);setSuccess("Family member added successfully.");await load();}catch(x){setError(x instanceof Error?x.message:"Unable to add family member.");}finally{setSaving(false);}}
  async function remove(row:Row){if(!confirm(`Remove ${row.name}?`))return;const s=getSocietySession();if(!s?.accessToken)return;const r=await fetch(`${API_URL}/society/member-management/family/${row.id}`,{method:"DELETE",headers:{Authorization:`Bearer ${s.accessToken}`}});const j=await r.json();if(!r.ok||!j.success)return setError(j.message);setSuccess("Family member removed.");await load();}
  const columns:Column<Row>[]=[{key:"name",header:"Family Member"},{key:"relation_type",header:"Relation"},{key:"primary_member_name",header:"Primary Member"},{key:"flat_no",header:"Flat",render:r=>`${r.wing_name}-${r.flat_no}`},{key:"building_name",header:"Building"},{key:"mobile",header:"Mobile",render:r=>r.mobile||"—"},{key:"status",header:"Status",render:r=><StatusBadge status={r.status==="ACTIVE"?"Active":"Inactive"}/>}];
  return <div><PageHeader title="Family Members" description={`${rows.length} family members in the selected society`} actions={<Button onClick={start}><Plus className="h-4 w-4"/> Add Family Member</Button>}/>{error&&<p className="mb-4 rounded-md bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{error}</p>}{success&&<p className="mb-4 rounded-md bg-[var(--color-success-bg)] p-3 text-sm text-[var(--color-success)]">{success}</p>}<Card><DataTable columns={columns} data={rows} keyField="id" searchFields={["name","primary_member_name","flat_no","mobile"]} rowActions={[{label:"Remove",icon:<Trash2 className="h-4 w-4"/>,onClick:r=>void remove(r),danger:true}]}/></Card>
  <Drawer open={open} onClose={()=>!saving&&setOpen(false)} title="Add Family Member" footer={<><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" form="family-form" loading={saving}>Save</Button></>}><form id="family-form" onSubmit={submit} className="flex flex-col gap-4"><Select label="Primary Member / Flat" required placeholder="Select member" value={form.primary_member_id&&form.flat_id?`${form.primary_member_id}:${form.flat_id}`:""} onChange={e=>{const[memberId,flatId]=e.target.value.split(":");setForm({...form,primary_member_id:memberId,flat_id:flatId});}} options={options.map(o=>({value:`${o.member_id}:${o.flat_id}`,label:`${o.name} — ${o.building_name}/${o.wing_name}/${o.flat_no}`}))}/><Input label="Full Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="Relation" required value={form.relation_type} onChange={e=>setForm({...form,relation_type:e.target.value})} options={relations.map(v=>({value:v,label:v.replaceAll("_"," ")}))}/><Input label="Mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><Input label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input label="Date of Birth" type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></form></Drawer></div>;
}
