"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CreditCard, IndianRupee, Package, ReceiptText, type LucideIcon } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { Input, Select } from "@/components/ui/Input";
import { StatusBadge } from "@/components/ui/Badge";
import { getSocietySession } from "@/lib/session";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:5000/api/v1";
type Plan={id:number;plan_code:string;plan_name:string;billing_cycle:string;price:string;status:string;max_buildings:number|null;max_flats:number|null;max_users:number|null};
type Subscription={id:number;society_id:number;plan_id:number;society_name:string;plan_name:string;subscription_number:string;start_date:string;end_date:string|null;status:string};
type Invoice={id:number;subscription_id:number;society_name:string;invoice_number:string;total_amount:string;balance_amount:string;due_date:string;status:string};
type Payment={id:number;society_name:string;invoice_number:string;amount:string;payment_mode:string;payment_date:string};
type Society={id:number;society_name:string};

export default function SubscriptionBillingPage(){
 const router=useRouter(); const [data,setData]=useState<{plans:Plan[];subscriptions:Subscription[];invoices:Invoice[];payments:Payment[]}>({plans:[],subscriptions:[],invoices:[],payments:[]});
 const [societies,setSocieties]=useState<Society[]>([]); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [busy,setBusy]=useState(false);
 const [plan,setPlan]=useState({plan_code:"",plan_name:"",billing_cycle:"MONTHLY",price:"",trial_days:"0",max_buildings:"",max_flats:"",max_users:""});
 const [assignment,setAssignment]=useState({society_id:"",plan_id:"",start_date:new Date().toISOString().slice(0,10),end_date:"",replace_existing:true});
 const [invoice,setInvoice]=useState({subscription_id:"",due_date:"",subtotal:"",tax_amount:"0"});
 const [payment,setPayment]=useState({invoice_id:"",amount:"",payment_mode:"UPI",reference_number:""});
 const auth=()=>{const session=getSocietySession();if(!session?.accessToken){router.replace("/login");return null;}return session.accessToken;};
 const load=useCallback(async()=>{const token=auth();if(!token)return;try{const [a,b]=await Promise.all([fetch(`${API_URL}/platform/subscriptions`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API_URL}/platform/societies`,{headers:{Authorization:`Bearer ${token}`}})]);const ar=await a.json(),br=await b.json();if(!a.ok||!ar.success)throw new Error(ar.message||"Unable to load billing data");setData(ar.data);setSocieties(br.data??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load billing data");}},[router]);
 useEffect(()=>{void load();},[load]);
 async function submit(path:string,body:unknown,method="POST"){const token=auth();if(!token)return;setBusy(true);setError("");setSuccess("");try{const response=await fetch(`${API_URL}${path}`,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.errors?.map((x:{msg?:string})=>x.msg).filter(Boolean).join(", ")||result.message||"Request failed");setData(result.data);setSuccess(result.message);return true;}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
 const money=(value:string|number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(value));
 const summaries:{icon:LucideIcon;label:string;value:string|number}[]=[{icon:Package,label:"Plans",value:data.plans.length},{icon:CreditCard,label:"Subscriptions",value:data.subscriptions.length},{icon:ReceiptText,label:"Open invoices",value:data.invoices.filter(x=>x.status!=="PAID"&&x.status!=="CANCELLED").length},{icon:IndianRupee,label:"Collected",value:money(data.payments.reduce((s,x)=>s+Number(x.amount),0))}];
 return <div><PageHeader title="Subscriptions & Platform Billing" description="Manage SaaS plans, society licences, invoices and collections."/>
  {error&&<p className="mb-4 rounded-lg bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]">{error}</p>}{success&&<p className="mb-4 rounded-lg bg-[var(--color-success-bg)] p-3 text-sm text-[var(--color-success)]">{success}</p>}
  <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summaries.map(({icon:Icon,label,value})=><Card key={label}><CardBody className="flex items-center gap-3"><div className="rounded-lg bg-[var(--color-primary)]/10 p-2 text-[var(--color-primary)]"><Icon className="h-5 w-5"/></div><div><p className="text-xs text-[var(--color-text-secondary)]">{label}</p><p className="font-semibold">{value}</p></div></CardBody></Card>)}</div>
  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader title="Create subscription plan"/><CardBody><form className="grid gap-3 sm:grid-cols-2" onSubmit={async(e:FormEvent)=>{e.preventDefault();if(await submit("/platform/subscription-plans",{...plan,price:Number(plan.price),trial_days:Number(plan.trial_days),max_buildings:plan.max_buildings?Number(plan.max_buildings):null,max_flats:plan.max_flats?Number(plan.max_flats):null,max_users:plan.max_users?Number(plan.max_users):null}))setPlan({...plan,plan_code:"",plan_name:"",price:""});}}><Input label="Plan Code" required value={plan.plan_code} onChange={e=>setPlan({...plan,plan_code:e.target.value})}/><Input label="Plan Name" required value={plan.plan_name} onChange={e=>setPlan({...plan,plan_name:e.target.value})}/><Select label="Billing Cycle" value={plan.billing_cycle} onChange={e=>setPlan({...plan,billing_cycle:e.target.value})} options={["MONTHLY","QUARTERLY","YEARLY","ONE_TIME"].map(x=>({label:x,value:x}))}/><Input label="Price" required type="number" min="0" value={plan.price} onChange={e=>setPlan({...plan,price:e.target.value})}/><Input label="Max Buildings (blank = unlimited)" type="number" value={plan.max_buildings} onChange={e=>setPlan({...plan,max_buildings:e.target.value})}/><Input label="Max Flats" type="number" value={plan.max_flats} onChange={e=>setPlan({...plan,max_flats:e.target.value})}/><Input label="Max Users" type="number" value={plan.max_users} onChange={e=>setPlan({...plan,max_users:e.target.value})}/><Input label="Trial Days" type="number" value={plan.trial_days} onChange={e=>setPlan({...plan,trial_days:e.target.value})}/><Button className="sm:col-span-2" type="submit" loading={busy}>Create Plan</Button></form></CardBody></Card>
   <Card><CardHeader title="Assign society subscription"/><CardBody><form className="grid gap-3 sm:grid-cols-2" onSubmit={async(e:FormEvent)=>{e.preventDefault();await submit("/platform/subscriptions",{...assignment,society_id:Number(assignment.society_id),plan_id:Number(assignment.plan_id)});}}><Select label="Society" required value={assignment.society_id} onChange={e=>setAssignment({...assignment,society_id:e.target.value})} placeholder="Select society" options={societies.map(x=>({label:x.society_name,value:String(x.id)}))}/><Select label="Plan" required value={assignment.plan_id} onChange={e=>setAssignment({...assignment,plan_id:e.target.value})} placeholder="Select plan" options={data.plans.filter(x=>x.status==="ACTIVE").map(x=>({label:`${x.plan_name} — ${money(x.price)}`,value:String(x.id)}))}/><Input label="Start Date" type="date" required value={assignment.start_date} onChange={e=>setAssignment({...assignment,start_date:e.target.value})}/><Input label="End Date" type="date" value={assignment.end_date} onChange={e=>setAssignment({...assignment,end_date:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={assignment.replace_existing} onChange={e=>setAssignment({...assignment,replace_existing:e.target.checked})}/> Replace current plan</label><Button className="sm:col-span-2" type="submit" loading={busy}>Assign Subscription</Button></form></CardBody></Card>
   <Card><CardHeader title="Generate invoice"/><CardBody><form className="grid gap-3 sm:grid-cols-2" onSubmit={async(e:FormEvent)=>{e.preventDefault();await submit("/platform/invoices",{...invoice,subscription_id:Number(invoice.subscription_id),subtotal:Number(invoice.subtotal),tax_amount:Number(invoice.tax_amount)});}}><Select wrapperClassName="sm:col-span-2" label="Subscription" required value={invoice.subscription_id} onChange={e=>setInvoice({...invoice,subscription_id:e.target.value})} placeholder="Select subscription" options={data.subscriptions.filter(x=>!["CANCELLED","EXPIRED"].includes(x.status)).map(x=>({label:`${x.society_name} — ${x.plan_name}`,value:String(x.id)}))}/><Input label="Due Date" required type="date" value={invoice.due_date} onChange={e=>setInvoice({...invoice,due_date:e.target.value})}/><Input label="Subtotal" required type="number" min="1" value={invoice.subtotal} onChange={e=>setInvoice({...invoice,subtotal:e.target.value})}/><Input label="Tax Amount" type="number" min="0" value={invoice.tax_amount} onChange={e=>setInvoice({...invoice,tax_amount:e.target.value})}/><Button className="sm:col-span-2" type="submit" loading={busy}>Generate Invoice</Button></form></CardBody></Card>
   <Card><CardHeader title="Record payment"/><CardBody><form className="grid gap-3 sm:grid-cols-2" onSubmit={async(e:FormEvent)=>{e.preventDefault();await submit(`/platform/invoices/${payment.invoice_id}/payments`,{amount:Number(payment.amount),payment_mode:payment.payment_mode,reference_number:payment.reference_number});}}><Select wrapperClassName="sm:col-span-2" label="Open Invoice" required value={payment.invoice_id} onChange={e=>setPayment({...payment,invoice_id:e.target.value})} placeholder="Select invoice" options={data.invoices.filter(x=>Number(x.balance_amount)>0&&!(["CANCELLED"].includes(x.status))).map(x=>({label:`${x.invoice_number} — ${x.society_name} — ${money(x.balance_amount)}`,value:String(x.id)}))}/><Input label="Amount" required type="number" min="1" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><Select label="Payment Mode" value={payment.payment_mode} onChange={e=>setPayment({...payment,payment_mode:e.target.value})} options={["UPI","NEFT","RTGS","CARD","ONLINE","CHEQUE","CASH"].map(x=>({label:x,value:x}))}/><Input wrapperClassName="sm:col-span-2" label="Reference Number" value={payment.reference_number} onChange={e=>setPayment({...payment,reference_number:e.target.value})}/><Button className="sm:col-span-2" type="submit" loading={busy}>Record Payment</Button></form></CardBody></Card>
  </div>
  <Card className="mt-5"><CardHeader title="Society subscriptions"/><CardBody className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-[var(--color-text-secondary)]"><tr>{["Society","Plan","Subscription","Period","Status","Action"].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.subscriptions.map(x=><tr className="border-t border-[var(--color-border)]" key={x.id}><td className="px-3 py-3 font-medium">{x.society_name}</td><td className="px-3 py-3">{x.plan_name}</td><td className="px-3 py-3">{x.subscription_number}</td><td className="px-3 py-3">{String(x.start_date).slice(0,10)} — {x.end_date?String(x.end_date).slice(0,10):"No expiry"}</td><td className="px-3 py-3"><StatusBadge status={x.status}/></td><td className="px-3 py-3"><Select aria-label="Change subscription status" value={x.status} onChange={e=>void submit(`/platform/subscriptions/${x.id}/status`,{status:e.target.value},"PATCH")} options={["ACTIVE","TRIAL","PAST_DUE","SUSPENDED","EXPIRED","CANCELLED"].map(v=>({label:v,value:v}))}/></td></tr>)}</tbody></table></CardBody></Card>
 </div>;
}
